# Generated by Django 5.0.5 on 2026-03-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("machine_id", models.CharField(db_index=True, max_length=64)),
                ("slot_no", models.CharField(max_length=32)),
                ("trade_no", models.CharField(db_index=True, max_length=32)),
                ("status", models.PositiveSmallIntegerField()),
                ("quantity", models.PositiveIntegerField()),
                ("stock", models.PositiveIntegerField()),
                ("capacity", models.PositiveIntegerField()),
                ("product_id", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("s_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("product_type", models.CharField(blank=True, max_length=128)),
                ("introduction", models.TextField(blank=True)),
                ("modify_type", models.CharField(blank=True, max_length=32)),
                ("lock_goods_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["machine_id", "slot_no"],
                "constraints": [
                    models.UniqueConstraint(fields=("machine_id", "slot_no"), name="uniq_producto_machine_slot")
                ],
            },
        ),
    ]
